// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtvsjtzwlnxplbzvrmkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dnNqdHp3bG54cGxienZybWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDY0NDMsImV4cCI6MjA2NjYyMjQ0M30.pRryyq8VI1FUyBeC5WUY7pZflJopeLsBkaHAkOuxmpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);